-- require("lsp_signature").setup()
-- require("navigator").setup({
-- 	keymaps = {
-- 		{ key = "gs", func = vim.lsp.buf.signature_help, desc = "signature_help" },
-- 		{ key = ",ff", func = vim.lsp.buf.format, mode = "n", desc = "format" },
-- 		{ key = ",ff", func = vim.lsp.buf.range_formatting, mode = "v", desc = "range format" },
-- 	},
-- 	lsp_installer = false, -- set to true if you would like use the lsp installed by lspinstall
-- 	debug = false,
-- 	lsp = {
-- 		diagnostic = {
-- 			underline = true,
-- 			virtual_text = false, -- show virtual for diagnostic message
-- 			update_in_insert = false, -- update diagnostic message in insert mode
-- 		},
-- 		diagnostic_virtual_text = false, -- show virtual for diagnostic message
-- 		diagnostic_update_in_insert = false, -- update diagnostic message in insert mode
-- 		disply_diagnostic_qf = false,
-- 		format_on_save = false,
-- 		disable_format_cap = { "pyright", "sumneko_lua", "tsserver", "yamlls", "html" },
-- 		disable_lsp = {
-- 			"angularls",
-- 			"flow",
-- 			"bashls",
-- 			"dockerls",
-- 			"julials",
-- 			"pylsp",
-- 			"jedi_language_server",
-- 			"jdtls",
-- 			"vimls",
-- 			"jsonls",
-- 			"solargraph",
-- 			"cssls",
-- 			-- "clangd",
-- 			-- "ccls",
-- 			"sqls",
-- 			"denols",
-- 			"graphql",
-- 			"dartls",
-- 			"dotls",
-- 			"kotlin_language_server",
-- 			"nimls",
-- 			"intelephense",
-- 			"vuels",
-- 			"phpactor",
-- 			"omnisharp",
-- 			"r_language_server",
-- 			-- "rust_analyzer",
-- 			"terraformls",
-- 			"svelte",
-- 			"texlab",
-- 			"clojure_lsp",
-- 			"elixirls",
-- 			"sourcekit",
-- 			"fsautocomplete",
-- 			"vls",
-- 			"hls",
-- 		},
-- 	},
-- })
--
